### PR TITLE
Update readme for building on macOS

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Homebrew provides glew and libdeflate

(Maybe closes #89)

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Steps needed to compile on macOS:

* Add `#include <stddef.h>` to utils.h (#105)

* Currently, only part of the server list is rendered:
	
	
		
	A workaround for this is commenting out these lines in hud.c:
	
	```
	glEnable(GL_SCISSOR_TEST);
	glScissor((settings.window_width - 600 * scaley) / 2.0F, 50 * scaley, 600 * scaley, (430 - 50) * scaley);
	```
	
	and this line:
	
	```
	glDisable(GL_SCISSOR_TEST);
	```
	
	This workaround results in this behavior when scrolling:

**Comment by xtreme8000** [comment]
> Currently, only part of the server list is rendered

This happens because the actual window size is different from what the game thinks it is, try adjusting your window dimensions in settings.

**Comment by SeekingMeaning** [comment]
Strangely, it seems multiplying each parameter of glScissor by 2 fixes the problem:

```c
   float scissor_x = (settings.window_width - 600 * scaley) / 2.0F;
   float scissor_y = 50 * scaley;
   float scissor_w = 600 * scaley;
   float scissor_h = (430 - 50) * scaley;

#if __APPLE__
   scissor_x *= 2;
   scissor_y *= 2;
   scissor_w *= 2;
   scissor_h *= 2;
#endif
```

```c
   glScissor(scissor_x, scissor_y, scissor_w, scissor_h);
```

**Comment by SeekingMeaning** [comment]
Bug with picking up intel:

<details open>
<summary>Before:</summary>
Screen Shot 2020-06-29 at 10 43 02 AM
</details>

<details open>
<summary>After:</summary>
Screen Shot 2020-06-29 at 10 43 12 AM
</details>

**Comment by xtreme8000** [comment]
possibly related to #145 and #146

**Pull request closed without merging**
